config/routes.rb
Rails.application.routes.draw do
  resources :infos
  resources :forests
  devise_for :users do 
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_scope :user do
    get '/admin' => 'devise/sessions#new', :as => :login
  end
  resources :images do 
  	resources :albums
  end
  resources :albums, :has_many => :images
  get '/admin/', to: 'devise/sessions#new'
  get 'info/index', to: 'infos#index'
  get '/album/:album_id/', to: 'albums#index'
  get '/album/:album_id/image', to: 'images#index'
  get '/album/:album_id/image/:image_id', to: 'images#show'
  root to: 'albums#index'
end

app/models/album.rb
class Album < ApplicationRecord
	validates :thumbnail, presence: true
	validates :title, presence: true
	has_many :images, :dependent => :destroy
	has_one_attached :thumbnail

	def thumbnail_f
  		return self.thumbnail.variant(resize: "175x175!").processed
	end
	 
	def thumbnail_b
		return self.thumbnail.variant(resize: "400x400!").processed
  	end
	
	def album_first
		return album.first
	end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_action :is_admin?, only: [:edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
    @images = Image.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:title, :thumbnail)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<div class="container" style="padding-top: 200px;height:100%;padding-left: 25px;width:50%">
  <div class="card" style="float:left;border-color:black;padding:75px">
    <div class="container" style="padding-left: 25px;%">
        <%= form_with(model: album, local: true) do |form| %>
          <% if album.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

              <ul>
                <% album.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <div class="form-row align-items-center">
              <div class="col-auto">
                <%= form.label :title, class: "form-check-label"%>
              </div>
              <div class="col-auto">
                <%= form.text_field :title %>
              </div>
            </div>
          </div>
          <br>

          <div class="field" style="padding-top: 25px;padding-bottom: 25px">
            <div class="form-row align-items-center">
              <div class="col-auto">
                <%= form.label :thumbnail, class: "form-check-label" %>
              </div>
              <div class="col-auto">
                <%= form.file_field :thumbnail %>
              </div>
            </div>
          </div>
          <br>
          <div class="actions">
            <%= form.button :Create, class: "btn btn-primary" %>
            <br>
          </div>
        <% end %>
      <br>
      <%= link_to 'Back', albums_path %>
        
      </div>
  </div>
</div>

app/views/albums/edit.html.erb
<%= render 'form', album: @album %>

app/views/albums/index.html.erb
<p>
<div class="container" style="min-width: 80%;padding-top:200px;padding-left:75px;float:left;height:50%;margin: 0">
    <h2 style="font-family:GT Walsheim;">albums</h2>
    <% @albums.each do |album| %>    
          <div class="card" style="border-color: white;width:auto;float:left;padding-left: 25px;padding-top:50px">
            <%= link_to image_tag(album.thumbnail_f), images_url(:id => album.id) %>
            <a class="nav-link" style="color: black;font-family:icofonts;font-size: 12px;text-align: center;"href="<%= images_url(:id => album.id) %>"><%= album.title %>  <span class="badge badge-info">(<%= album.images.count %>)</span><% if current_user && current_user.admin? %>
	            <p><%= button_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %><%= link_to 'Change Thumbnail', edit_album_path(album), class:"btn btn-outline-primary btn-sm" %>
	            <% end %></a>
          </div>
    <% end %>
    <div class="container" style="float:left;padding-left: 50px;padding-top: 50px;padding-bottom: 100px">
    <% if current_user && current_user.admin? %>
    	<%= link_to 'New Album', new_album_path, class: 'btn btn-dark btn-sml' %>
    <% end %>
</div>

app/views/albums/new.html.erb
<%= render 'form', album: @album %>

app/views/albums/show.html.erb
<div class="container" style="padding-top:200px;padding-left:250px;float:left;">
 <div class="card" style="width:400px;height:auto;padding:50px">
  <p>
    
   <h2 style="font-family:GT Walsheim;font-size:28;text-align: center"> <%= @album.title %> </h2>
  </p>
  <%= image_tag(@album.thumbnail_b) %>
    <div class="container" style="width:auto">
      <br>
      <div class ="container" style="padding-top: 10px">
        <%= link_to 'Add Images to Album...', new_image_path, class: "btn btn-outline-primary btn-sm" %> 
      </div>
      <br>
      <div class ="container" style="padding-top: 10px">
        <%= link_to 'Change Album', edit_album_path(@album), class: "btn btn-outline-primary btn-sm" %> 
        <%= link_to 'Back', albums_path, class: "btn btn-outline-primary btn-sm" %>
      </div>
    <div>
  </div>
</div>