config/routes.rb
Rails.application.routes.draw do
  resources :infos
  resources :forests
  devise_for :users do 
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_scope :user do
    get '/admin' => 'devise/sessions#new', :as => :login
  end
  resources :images do 
  	resources :albums
  end
  resources :albums, :has_many => :images
  get '/admin/', to: 'devise/sessions#new'
  get 'info/index', to: 'infos#index'
  get '/album/:album_id/', to: 'albums#index'
  get '/album/:album_id/image', to: 'images#index'
  get '/album/:album_id/image/:image_id', to: 'images#show'
  root to: 'albums#index'
end

app/models/forest.rb
class Forest < ApplicationRecord
    has_one_attached :file_thumbnail
    has_one_attached :file

	def self.search(search)
		if search
			where('description LIKE ?',"%#{search}%")
		else
			Forest.all
		end
	end
end

app/controllers/forests_controller.rb
class ForestsController < ApplicationController
  before_action :set_forest, only: [:show, :edit, :update, :destroy]
  before_action :is_admin?, only: [:edit, :update, :destroy]
  # GET /forests
  # GET /forests.json
  def index
    @forests = Forest.search(params[:search])
  end

  # GET /forests/1
  # GET /forests/1.json
  def show
  end

  # GET /forests/new
  def new
    @forest = Forest.new
  end

  # GET /forests/1/edit
  def edit
  end

  # POST /forests
  # POST /forests.json
  def create
    @forest = Forest.new(forest_params)

    respond_to do |format|
      if @forest.save
        format.html { redirect_to @forest, notice: 'Forest was successfully created.' }
        format.json { render :show, status: :created, location: @forest }
      else
        format.html { render :new }
        format.json { render json: @forest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forests/1
  # PATCH/PUT /forests/1.json
  def update
    respond_to do |format|
      if @forest.update(forest_params)
        format.html { redirect_to @forest, notice: 'Forest was successfully updated.' }
        format.json { render :show, status: :ok, location: @forest }
      else
        format.html { render :edit }
        format.json { render json: @forest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forests/1
  # DELETE /forests/1.json
  def destroy
    @forest.destroy
    respond_to do |format|
      format.html { redirect_to forests_url, notice: 'Forest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forest
      @forest = Forest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def forest_params
      params.require(:forest).permit(:description, :file, :search)
    end
end

app/helpers/forests_helper.rb
module ForestsHelper
end

app/views/forests/_form.html.erb
<div class="container" style="padding-top: 200px;height:100%;padding-left: 25px;width:50%">
  <div class="card" style="float:left;border-color:black;padding:75px">
  <%= simple_form_for(@forest) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="field">
      <%= f.label :file %>
      <%= f.file_field :file, direct_upload: true,
      accept: 'application/pdf,
      application/zip/application/vnd.openxmlformats-officedocument.wordprocessingml.document',  class: "form-control" %>
    </div>

    
    <div class="form-inputs">
      <%= f.label :description, "Name" %>
      <%= f.text_field :description, class: "form-control" %>
    </div>

    <br>
    <div class="form-actions">
      <%= f.button :submit, class: "btn btn-primary" %>
    </div>
    <br>
    <%= link_to 'Back', forests_path %>

  <% end %>
  </div>
</div>

app/views/forests/edit.html.erb
<%= render 'form', forest: @forest %>

app/views/forests/index.html.erb
<p>
<%= csrf_meta_tag %>
<div class="container" style="min-width: 80%;padding-top:200px;padding-left:75px;float:left;height:50%;margin: 0">

    <h2 style="font-family:GT Walsheim;">docs</h2>

  <div class="Search" style="margin: auto;float:center">
    <br>
    <%= form_tag(forests_path, method: :get) do %>
      <%= text_field_tag(:search, params[:search]) %>
      <%= submit_tag "Search", :description => nil, class: "btn btn-dark" %>
    <% end %>
  </div>
  <br>


  <table class="table table-striped">
    <thead>
      <tr>
        <th>title</th>
        <th>filename</th>
        <th>Preview</th>
        <% if current_user && current_user.admin? %>
        <th>Remove</th>
        <% end %>
        <th>Download</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @forests.each do |forest| %>
        <tr>
          <td><%= forest.description%></td>
          <% if forest.file.attached? %>
            <td><%= forest.file.blob.filename %>
          <% else %>
            <td>n/a</td>
          <% end %>
          <% if current_user && current_user.admin? %>
            <td><%= link_to 'Edit', edit_forest_path(forest) %></td>
            <td><%= button_to 'Destroy', forest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
          <td><% if forest.file.attached? %>
            <%= link_to 'View File', forest.file %>
          </td><td>
            <%= link_to 'Download', forest.file, download: '' %>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <% if current_user && current_user.admin? %>
    <%= link_to 'Add file...', new_forest_path %>
  <% end %>
</div>

app/views/forests/new.html.erb
<%= render 'form', forest: @forest %>

app/views/forests/show.html.erb
<p>
  <strong>Description:</strong>
  <%= @forest.description %>
</p>

<% if @forest.file.attached? %>
  <%= link_to 'View File', @forest.file %>
  <%= link_to 'Download', @forest.file, download: '' %>
  <%= @forest.file.blob.filename %>
<% end %>


<%= link_to 'Edit', edit_forest_path(@forest) %> |
<%= link_to 'Back', forests_path %>