config/routes.rb
Rails.application.routes.draw do
  resources :infos
  resources :forests
  devise_for :users do 
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_scope :user do
    get '/admin' => 'devise/sessions#new', :as => :login
  end
  resources :images do 
  	resources :albums
  end
  resources :albums, :has_many => :images
  get '/admin/', to: 'devise/sessions#new'
  get 'info/index', to: 'infos#index'
  get '/album/:album_id/', to: 'albums#index'
  get '/album/:album_id/image', to: 'images#index'
  get '/album/:album_id/image/:image_id', to: 'images#show'
  root to: 'albums#index'
end

app/models/image.rb
class Image < ApplicationRecord
  validates :title, presence: true
  validates :drawing, presence: true
  belongs_to :album
  has_rich_text :body
  has_one_attached :drawing

	def drawing_f
  		return self.drawing.variant(resize: "200x200!").processed
 	end

 	def drawing_big
  		return self.drawing.variant(resize: "400x400!").processed
 	end

 	def drawing_c
  		return self.drawing.variant(resize: "175x175!").processed
	 end
	 


 	def add_one
 		self.id + 1
 	end

 	def take_one
 		self.id - 1
 	end

 	def next_1
 		self.add_one unless !album.images.where("id > ?", self.id).exists?
  	end

  	def prev_1
 		self.take_one unless !album.images.where("id < ?", self.id).exists?
  	end

  	def has_next?
  		album.images.where("id > ?", self.id).exists?
  	end

  	def has_prev?
  		album.images.where("id < ?", self.id).exists?
  	end

end




##Image.offset(self.id).limit(1).order("id ASC").first
##self.add_one unless !album.images.where("id > ?", self.id).exists?

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :find_album, only: [:update, :destroy]
  before_action :is_admin?, only: [:edit, :update, :destroy]
  # GET /images
  # GET /images.json
  def index
    @album = Album.find(params[:id]) 
    @images = Image.find(params[:id]) if params[:album_id]
  end

  # GET /images/1
  # GET /images/1.json
  def show 
    @image = Image.find(params[:id])
    @next_image = @image.next_1
  end

  # GET /images/new
  def new
    @image = Image.new
    @album = Album.all
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def find_album
      @album = Album.find(params[:album_id])
    end

    def find_image
      @image = @album.images.find(params[:id])
    end

    def set_image
      @image = Image.find(params[:id])
    end
    
    def image_params
      params.require(:image).permit(:title, :body, :drawing, :album_id)
    end
    # Only allow a list of trusted parameters through.
end

app/helpers/images_helper.rb
module ImagesHelper
	
end

app/views/images/_form.html.erb
<%= javascript_pack_tag 'application' %>
<div class="container" style="padding-top: 200px;height:100%;padding-left: 25px;width:50%">
  <div class="card" style="float:left;background-color:#f1f8ff">
    <div class="container" style="padding-left: 25px;padding-top: 25px">
      <%= form_with(model: image, local: true) do |form| %>
        <% if image.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

            <ul>
              <% image.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= form.label :title, "Enter the title:" %>
          <%= form.text_field :title, class: "form-control" %>
        </div>
        <br>
        <div class="field">
          <%= form.label :body, "Description" %>
          <%= form.text_area :body, :class => "form-control", :rows => 3 %>
        </div>

        <div class="field">
          <%= form.label :drawing, "Select your image" %>
          <%= form.file_field :drawing, multiple: false, direct_upload: true, class: "form-control" %>
        </div>

        <br>


      
        <div class="form-control; height:auto">
          <%= form.label :album_id, "Select your Album" %>
            <%= form.collection_radio_buttons(:album_id, @album, :id, :title) do |b| b.label(:"data-value" => b.value, class: " form-control btn btn-outline-info btn-sm") { b.radio_button + " " + b.text }
          end
          %>
        <div class="actions" style="padding-left: 550px">
          <br>
          <%= form.submit "Upload" %>
        </div>
        <br>
      <% end %>

      

    </div>
  </div>
</div>
<div class="container" style="float:left">
  <%= link_to 'Back', root_path %>
</div>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
  <div class="container" style="min-width: 80%;padding-top:200px;padding-left:75px;float:left;height:50%;margin: 0">
    <h2 style="font-family:GT Walsheim;">
      <%= @album.title %>
    </h2>
    <p style="margin: 0;float:right">
     <%= link_to 'Back to Album', albums_path, class: "btn btn-outline-primary btn-sm" %>
    </p>
    <% (@album.images).each do |img| %>
      <div class="card" style="border-color: white;width:auto;float:left;padding-left: 25px;padding-top:50px">
        <% if img.drawing.attached? %>
          <%= image_tag(img.drawing_f)%>
        <% end %>
        <%= link_to img.title, img, :style => "color: black;font-family:icofonts;font-size: 12px;text-align: center;border-color:white"%><% if current_user && current_user.admin? %>
              <p><%= button_to 'Destroy', img, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %>
              <% end %></a>
      </div>
    <% end %>
  </div>

  <div class="container" style="padding-top:75px;padding-left: 160px;float:left">
    <% if current_user && current_user.admin? %>
      <%= link_to "Upload new drawing", new_image_path(:album_id => @album.id), class: "btn btn-dark" %>
    <% end %>
  </div>

</div>

app/views/images/new.html.erb
<%= render 'form', image: @image %>

app/views/images/show.html.erb
<div class="container" style="padding-top: 200px;height:100%;padding-left: 75px;">
	<div class="container" style="width:25%;float:left;padding-left: 100px;padding-right:25px;padding-bottom:50px;text-align: center">
	  	<a class="nav-link" style="float:left;color: black;font-family: sans-serif;font-size: 16px;border: 2px solid black"href="<%= images_path(:id => @image.album_id) %>">Back to Album</a>
	</div>
	<div class="container" style="">
      <div class="card" style="min-width: 75%;margin:auto;border-style:solid;border-width:2px;padding:50px">
      	<div class="container" style="text-align: center">
	      	<% if @image.has_prev? %>
	      		<button type="button" class="btn btn-default btn-lg">
	      			<a class="glyphicon glyphicon-align-left" style="float:left;color:black;" href="<%= @image.prev_1 %>">< </a>
	      		</button>
	      	<% end %>
	      	<%= image_tag(@image.drawing_big) %>
	      	<% if @image.has_next? %>
				<button type="button" class="btn btn-default btn-lg">
	      			<a class="glyphicon glyphicon-menu-align-right" style="float:right;color:black;" href="<%= @next_image %>">></a>
	      		</button>
	      	<% end %>
      	</div>
      </div>

     
	 
	  <div class="container" style="width:100%;margin:auto;position:fixed;padding-top: 50px">
		  <p class="lead"><%= @image.title %></p>
		  <hr class="my-4" style="padding-left: 25px">
		  	<%= @image.body %>
		  </hr>
	  </div>
</div>