config/routes.rb
Rails.application.routes.draw do
  resources :infos
  resources :forests
  devise_for :users do 
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_scope :user do
    get '/admin' => 'devise/sessions#new', :as => :login
  end
  resources :images do 
  	resources :albums
  end
  resources :albums, :has_many => :images
  get '/admin/', to: 'devise/sessions#new'
  get 'info/index', to: 'infos#index'
  get '/album/:album_id/', to: 'albums#index'
  get '/album/:album_id/image', to: 'images#index'
  get '/album/:album_id/image/:image_id', to: 'images#show'
  root to: 'albums#index'
end

app/views/layouts/_sidebar.html.erb
<div class="navbar" style="width:10%;float:left;"> 
  <a class="nav-link active" style="color:grey;font-family:icofonts;"href="<%= info_index_path %>"> Home </h2>

  <ul class="nav flex-column" style="padding-top: 200px">

    <li class="nav-item">
      <a class="nav-link active" style="color: black;font-family:GT Walsheim;"href="<%= info_index_path %>">info</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" style="color: black;font-family:GT Walsheim;"href="<%= albums_path %>">images</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" style="color: black;font-family:GT Walsheim;"href="<%= forests_path %>">forests</a>
    </li>
  </ul>
</div>

  <div class="container" style="min-width:100%;text-align:right">
     <% if user_signed_in? %>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-outline-dark btn-sm" %>        
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HananaSplit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'lightbox2.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/sidebar' %>
    <br>
    <div class="container" style="padding-left: 250px">
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
    <%= yield :after_js %>
  </body>
</html>